lojas/urls.py
from django.conf.urls import url

from . import views

app_name = 'lojas'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signedin/$', views.signedin, name='signedin'),
    url(r'^carrinho/$', views.carrinho, name='carrinho'),
    url(r'^finalizar_compra/$', views.finalizar_compra, name='finalizar_compra'),
    url(r'^pedidos/$', views.pedidos, name='pedidos'),
    url(r'^(?P<produto_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<produto_id>[0-9]+)/add_produto/$', views.add_produto, name='add_produto'),
    url(r'^carrinho/remove_produto/$', views.remove_produto, name='remove_produto'),

]

lojinha/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^accounts/login/$', auth_views.login, {'template_name': 'lojas/login.html'}),
    url(r'^lojas/', include('lojas.urls')),
    url(r'^admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),
]

lojas/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class Produto(models.Model):
    nome = models.CharField(max_length=200)
    quantidade = models.IntegerField(default=1)
    preco = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    def remover_estoque(self, quantidade):
        self.quantidade -= int(quantidade)
        self.save()

    def __str__(self):
        return self.nome + ' - R$ ' + "%01.2f" % self.preco + ' (' + str(self.quantidade) + ')'


class Carrinho(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="carrinho", default=2)
    def adicionar_produto(self, produto, quantidade):
        try:
            item = self.itens_carrinho.get(pk=produto.id)
        except ItemCarrinho.DoesNotExist:
            item = ItemCarrinho(carrinho=self, produto=produto, quantidade=0)
        item.quantidade += int(quantidade)
        item.save()
        return item

    def qtd_itens(self):
        return self.itens_carrinho.count()

    def custo_total(self):
        total = float(0)
        for item in self.itens_carrinho.all():
            total += float(item.produto.preco)
        return float(total)

    def __str__(self):
        return "(id: %d) %d produtos, total: R$ %s" % (self.id, self.qtd_itens(), ("%01.2f" % self.custo_total()))


class ItemCarrinho(models.Model):
    carrinho = models.ForeignKey(Carrinho, on_delete=models.CASCADE, related_name="itens_carrinho")
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.IntegerField(default=1)

    def __str__(self):
        return "%s (%s) Preco Unitario: R$ %s" % (self.produto.nome, str(self.quantidade), ("%01.2f" % self.produto.preco))

class StatusPedido(models.Model):
    nome = models.CharField(max_length=200)

    def __str__(self):
        return self.nome

class Pedido(models.Model):
    status = models.ForeignKey(StatusPedido, related_name="pedidos", default=1)

    def qtd_itens(self):
        return self.itens_pedido.count()

    def custo_total(self):
        total = float(0)
        for item in self.itens_pedido.all():
            total += float(item.produto.preco)
        return float(total)

    def __str__(self):
        return "(%s) %d produtos, total: R$ %s" % (self.status.nome, self.qtd_itens(), ("%01.2f" % self.custo_total()))


class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE, related_name="itens_pedido")
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.IntegerField(default=1)

    def __str__(self):
        return "Pedido %d: %d produtos, total: R$ %s" % (self.id, self.qtd_itens(), ("%01.2f" % self.custo_total()))

        return "(id: %d) %d produtos, total: R$ %s" % (self.id, self.qtd_itens(), ("%01.2f" % self.custo_total()))

lojas/views.py
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from .models import Produto, Carrinho, Pedido
from .helpers import CriadorPedido, PegaCarrinho
from django.contrib.auth.decorators import login_required


@login_required()
def index(request):
    produtos = Produto.objects.all()
    context = {'produtos': produtos}
    return render(request, 'lojas/index.html', context)


@login_required()
def detail(request, produto_id):
    produto = get_object_or_404(Produto, pk=produto_id)
    return render(request, 'lojas/detail.html', {'produto': produto})


@login_required()
def add_produto(request, produto_id):
    produto = get_object_or_404(Produto, pk=produto_id)
    carrinho = PegaCarrinho(request.user).carrinho()
    quantidade = request.POST['quantidade']
    carrinho.adicionar_produto(produto, quantidade)
    return HttpResponseRedirect(reverse('lojas:carrinho'))


@login_required()
def remove_produto(request):
    item_id = request.POST['item_id']
    carrinho = PegaCarrinho(request.user).carrinho()
    item = get_object_or_404(carrinho.itens_carrinho, pk=item_id)
    item.delete()
    return HttpResponseRedirect(reverse('lojas:carrinho'))


@login_required()
def carrinho(request):
    carrinho = PegaCarrinho(request.user).carrinho()
    itens = carrinho.itens_carrinho.all()
    return render(request, 'lojas/carrinho.html', {'itens': itens})


@login_required()
def finalizar_compra(request):
    carrinho = PegaCarrinho(request.user).carrinho()
    criador_pedido = CriadorPedido(carrinho)

    if criador_pedido.save():
        return HttpResponseRedirect(reverse('lojas:pedidos'))
    else:
        msg = "Nao foi possivel fechar a compra %s" % criador_pedido.string_errors()
        return render(request, 'lojas/carrinho.html', {'itens': carrinho.itens_carrinho.all(), 'msg': msg})


@login_required()
def pedidos(request):
    pedidos_usuario = Pedido.objects.all()
    return render(request, 'lojas/pedidos/index.html', {'pedidos': pedidos_usuario})


@login_required()
def signedin(request):
    PegaCarrinho(request.user).carrinho()
    return HttpResponseRedirect(reverse('lojas:index'))

lojas/templates/lojas/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Lojinha do Apu{% endblock %}</title>
</head>

<body>
<div id="sidebar">
    {% block sidebar %}
        <h1>Apu's Kwik-E-Mart</h1>
        <nav>
            <a href="{% url 'lojas:index' %}">Produtos</a> |
            <a href="{% url 'lojas:carrinho' %}">Carrinho</a> |
            <a href="{% url 'lojas:pedidos' %}">Pedidos</a> |
            <a href="{% url 'logout' %}">Deslogar</a> |

        </nav>

    {% endblock %}
</div>

<div id="content">
    {% block content %}{% endblock %}
</div>
</body>
</html>

lojas/templates/lojas/carrinho.html
{% extends "lojas/base.html" %}

{% block title %}Lojinha - Carrinho{% endblock %}

{% block content %}
    <h1>Meu Carrinho</h1>
    <p style="color:red">{{ msg }}</p>
    <ol>
        {% for item in itens %}
            <li> {{ item }}</li>
            <form action="{% url 'lojas:remove_produto'%}" method="post">
                {% csrf_token %}
                <input type="hidden" name="item_id" id="item_id" value="{{ item.id }}"/>
                <input type="submit" value="Remover do Carrinho"/>
            </form>
        {% endfor %}
    </ol>
    <form action="{% url 'lojas:finalizar_compra' %}" method="post">
        {% csrf_token %}
        {% if itens.count > 0 %}
            <input type="submit" value="Finalizar Compra"/>
        {% endif %}
    </form>
{% endblock %}

lojas/templates/lojas/detail.html
{% extends "lojas/base.html" %}

{% block title %}Lojinha - Produto{% endblock %}

{% block content %}

<h1>Detalhes do produto</h1>
<p><b>Nome:</b> {{ produto.nome }}</p>
<p><b>Quantidade disponível:</b> {{ produto.quantidade }}</p>

<h2>Comprar Produto:</h2>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'lojas:add_produto' produto.id %}" method="post">
    {% csrf_token %}
    <label for="quantidade">Quantidade Desejada:</label>
    <input type="number" name="quantidade" id="quantidade" value="1"/>
    <input type="submit" value="Adicionar ao Carrinho"/>
</form>
{% endblock %}

lojas/templates/lojas/index.html
{% extends "lojas/base.html" %}

{% block title %}Lojinha - Produtos{% endblock %}

{% block content %}
<h1>Listagem de Produtos</h1>
<ol>
    {% for produto in produtos %}
        <li><a href="{%  url 'lojas:detail' produto.id %}">{{ produto.nome }} ({{ produto.quantidade }})</a></li>
    {% endfor %}
</ol>
{% endblock %}

lojas/templates/lojas/login.html
{% extends "lojas/base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="/lojas/signedin/" />
</form>

{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'password_reset' %}">Lost password?</a></p>

{% endblock %}

lojas/templates/lojas/pedidos/index.html
{% extends "lojas/base.html" %}

{% block title %}Lojinha - Carrinho{% endblock %}

{% block content %}
<h1>Meus Pedidos</h1>
<ol>
    {% for pedido in pedidos %}
        <li> {{ pedido }}</li>
    {% endfor %}
</ol>
{% endblock %}